################ Korean language ##################
[ko]
languageName = "한국어"
languageCode = "ko"
contentDir = "content/ko"
weight = 1
################ English language ##################
[en]
languageName = "English"
languageCode = "en"
contentDir = "content/en"
weight = 2
